### ISSUE TITLE
[Bug]: Can't create new world when using ServerConfigUpdater on Linux

### ISSUE THREAD

**Issue by DarkShadow44** [TheIllusiveC4/Diet#135]
### What happened?

I tried to create a new world, and after the spawn area was prepared, I get the message "Server sent an invalid packet" and I get thrown back into the main menu.

I know the backtrace isn't from this mod, but it goes away if this mod is not sent a config update from ServerConfigUpdater, I hope you can help me with that.

### How do you trigger this bug?

1. Be on Linux - doesn't seem to happen on Windows for some reason
2. Use this mod and the ServerConfigUpdater mod
3. Configure ServerConfigUpdater to update Diet mod (see below)
4. Create new world

### Forge Version

Forge 40.1.25

### Mod Version

Diet Forge 1.18.2 - 1.3.1.0

### Other Relevant Mod Versions

ServerConfigUpdater 2.0

serverconfigupdater-common.toml contents:
```
["Version Configuration"]
	versions = ["1=diet"]
```

### Relevant Log Outputs

Exception that gets thrown:
```
[05Jun2022 17:46:01.514] [Netty Local Client IO #0/ERROR] [net.minecraft.network.Connection/]: Received class net.minecraft.network.protocol.game.ClientboundDisconnectPacket that couldn't be processed
java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl cannot be cast to class net.minecraft.network.protocol.game.ClientGamePacketListener (net.minecraft.client.multiplayer.ClientHandshakePacketListenerImpl and net.minecraft.network.protocol.game.ClientGamePacketListener are in module minecraft@1.18.2 of loader 'TRANSFORMER' @1bb172dd)
	at net.minecraft.network.protocol.game.ClientboundDisconnectPacket.m_5797_(ClientboundDisconnectPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23530!/:?]
	at net.minecraft.network.Connection.m_129517_(Connection.java:168) ~[client-1.18.2-20220404.173914-srg.jar%23530!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:153) [client-1.18.2-20220404.173914-srg.jar%23530!/:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:53) [client-1.18.2-20220404.173914-srg.jar%23530!/:?]
```

[latest.log](https://pastebin.com/qTSh2wfL)
[debug.log](https://pastebin.com/GvZhU0AR)

**Comment by TheIllusiveC4** [comment]
Does this happen with only those two mods installed and nothing else?

**Comment by DarkShadow44** [comment]
Yes, only those two.

**Comment by TheIllusiveC4** [comment]
Hm, very strange. I'm not sure what would cause this issue on Diet's end, and I don't exactly have a Linux machine to properly test the bug. I'll try to dig a little deeper, but I might not be able to resolve this in the end.
