### ISSUE TITLE
[Bug]: opening inventory it crashes with button appear in inventory "false"

### ISSUE THREAD

**Issue by Masmelao** [TheIllusiveC4/Diet#202]
### Minecraft Version

1.20.1

### What happened?

when i change setting, button appear in inventory to "false" and open inventory it crashes the game.

### How do you trigger this bug?

1. Change buttons appear on inventory to false.
2. Open inventory.
3. It crashes :(
![Screenshot 2024-09-25 234138](https://github.com/user-attachments/assets/d39f9eaa-7bd4-4490-8e71-17e0d46937aa)
this are the mods i tested with....
![Screenshot 2024-09-25 235034](https://github.com/user-attachments/assets/64efc808-da9d-4bab-a83c-9bb1ada1fc26)

### Loader

Fabric

### Loader Version

fabric - 0.16.5

### API Version

fabric-api-0.92.2+1.20.1

### Mod Version

diet-fabric-2.1.1+1.20.1

### Relevant Log Outputs

net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.16.5-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.5.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4068.method_25394(net.minecraft.class_332, int, int, float)" because "$$4" is null
	at net.minecraft.class_437.method_25394(class_437.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 6 more

**Comment by Midnight-GHub** [comment]
Facing the same issue here as well!
